# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1912900357aa88844c7430cabb90f0dccf0829ee8a60e3a7c2b762db054f7b863d763f2ade7a1d8adc32ad99d0a828da6ce2f3b4084d2002f31c91d421948935

test:
  secret_key_base: a3f494d5637cfb8e0331f58eb94243b4d501124d3f87e965a1b64351ed1db15141f673a237472e5ea4bc9089184a1156d556e84798958ad9c55608a88d859e65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
